language: node_js
node_js:
- stable
install: npm install
services:
- mongodb
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: XwJWTFhVCPNF1MLtQC4R4pnj+0kdpmY49fM0llQoh+0dfDSCf0U2qN0mpZvVkTkwDPIeWEcMiSQ6gNHUkDReT1t0fXNniHo2hU92N2eITn2dnDe0dxzTnzp0yQS5aAjZl0O0Rcy6vWxs2+/kG3zbL1xTwOewek3WAK6bE6BckHQYScPZWMo64w+Dnnv4WMwnXMJ81mFUueiJ8f5Ra6W1nLuWCxU4CY86/zYBUD/saHoD0kPKTjQBUG0650hlP6E7suS0/gGJ71Lga3P2n216zdelW6tVf/YCj178UQCRIiTJmm1wRsuZF0PUvEp+C40fv5JL4/j/S1mUWE1lAtEShZuaHRCcik3dsu3cbxMp8pVCc77C1jk95acDJv0sW/rzgIXlvvM4eriXq+40Zl9Fn0Boey2DK/1Fpk9rD1ucAPX7d2jN/uBfTZ2iBanr6VU3WoqGjYZdY+J0biau2N6ntAxTnEgv3qzBwd3WK+Aadp25cY4wX+1Ig0I+1mfeSjfZieWjc464Jfwjj4/o5joUbBZy9nKAKu68T4Nx/hVK24H2/Y3illbButiAZNdcUIBXjgU/9VAJPtCKQWIBeF4qquJ8XPaGdpoVp2T4ewWBHFudwWGravQUntMdzuJIQUg9VR2h0d0WnbxHaIOVKe9YTWMo0C8zso0pvF0rqcShSYc=
  app: my-app-projects
  on:
    repo: GabrielleEaston/mongodb-mongoose-express-ci
    run:
    - "node seed/userProjects.js"
